Workflows(docker-build): issue num from branch

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -47,17 +47,23 @@ jobs:
 
             if [[ "${{ github.event.pull_request.milestone }}" != "null" ]]; then
               MILESTONE=milestone-${{ github.event.pull_request.milestone.number }}
-              echo MILESTONE=$MILESTONE
               docker tag $IMAGE_NAME $IMAGE_ID:$MILESTONE
               docker push $IMAGE_ID:$MILESTONE
               echo "docker push $IMAGE_ID:$MILESTONE"
             fi
-
-            ISSUE=$(echo ${{ github.event.pull_request.issue_url }} | cut -d '/' -f 8)
-            echo ISSUE=$ISSUE
-            docker tag $IMAGE_NAME $IMAGE_ID:$ISSUE
-            docker push $IMAGE_ID:$ISSUE
-            echo "docker push $IMAGE_ID:$ISSUE"
+            
+            # as a workaround as we cannot access the issue number from the PR
+            # we can use the branch name as they are expected to start from issuue number
+            ISSUE_NUMBER=$(echo ${{ github.ref_name }} | cut -d '-' -f 0)
+            if [[ "$ISSUE_NUMBER" =~ ^[0-9]+$ ]]; then
+              echo "ISSUE_NUMBER is a number: $ISSUE_NUMBER"
+              docker tag $IMAGE_NAME $IMAGE_ID:$ISSUE_NUMBER
+              docker push $IMAGE_ID:$ISSUE_NUMBER
+              echo "docker push $IMAGE_ID:$ISSUE_NUMBER"
+            else
+              echo "Branch name does not start with a number: ${{ github.ref_name }}"
+              exit 1  # Fail the GitHub Action
+            fi
           fi
           
           # everything is also pushed to dev
